// <auto-generated />
using System;
using BccSafety.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BccSafety.Infrastructure.Migrations
{
    [DbContext(typeof(BccSafetyDbContext))]
    [Migration("20260828131250_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.ActionToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("scope_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_action_token");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_action_token_person_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_action_token_token_hash");

                    b.ToTable("action_token", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Advisory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("EventTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_type_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_advisory");

                    b.HasIndex("EventTypeId")
                        .HasDatabaseName("ix_advisory_event_type_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_advisory_tenant_id");

                    b.ToTable("advisory", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("WarningsAtAssignment")
                        .HasColumnType("jsonb")
                        .HasColumnName("warnings_at_assignment");

                    b.Property<string>("WithdrawalReason")
                        .HasColumnType("text")
                        .HasColumnName("withdrawal_reason");

                    b.Property<DateTimeOffset?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.HasKey("Id")
                        .HasName("pk_assignment");

                    b.HasIndex("AssignedBy")
                        .HasDatabaseName("ix_assignment_assigned_by");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_assignment_person_id");

                    b.HasIndex("ShiftId")
                        .HasDatabaseName("ix_assignment_shift_id");

                    b.ToTable("assignment", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_person_id");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("ActorPersonId")
                        .HasDatabaseName("ix_audit_log_actor_person_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_audit_log_tenant_id");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Availability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("From")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("from");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset>("Until")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("until");

                    b.HasKey("Id")
                        .HasName("pk_availability");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_availability_person_id");

                    b.ToTable("availability", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.CalendarMismatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.HasKey("Id")
                        .HasName("pk_calendar_mismatch");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_calendar_mismatch_event_id");

                    b.ToTable("calendar_mismatch", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.CalendarSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("IcsUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ics_url");

                    b.Property<string>("LastSyncStatus")
                        .HasColumnType("text")
                        .HasColumnName("last_sync_status");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_calendar_source");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_calendar_source_tenant_id");

                    b.ToTable("calendar_source", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.CandidateEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CalendarSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("calendar_source_id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end");

                    b.Property<string>("IcsUid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ics_uid");

                    b.Property<string>("LocationText")
                        .HasColumnType("text")
                        .HasColumnName("location_text");

                    b.Property<string>("RecurrenceId")
                        .HasColumnType("text")
                        .HasColumnName("recurrence_id");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_candidate_event");

                    b.HasIndex("CalendarSourceId", "IcsUid", "RecurrenceId")
                        .IsUnique()
                        .HasDatabaseName("ix_candidate_event_calendar_source_id_ics_uid_recurrence_id");

                    b.ToTable("candidate_event", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.CheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<Guid>("ByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("by_person_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_check_in");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_check_in_assignment_id");

                    b.HasIndex("ByPersonId")
                        .HasDatabaseName("ix_check_in_by_person_id");

                    b.ToTable("check_in", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Function")
                        .HasColumnType("text")
                        .HasColumnName("function");

                    b.Property<bool>("IsEmergencyNumber")
                        .HasColumnType("boolean")
                        .HasColumnName("is_emergency_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_contact");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_contact_tenant_id");

                    b.ToTable("contact", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("FileRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_ref");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("VersionLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version_label");

                    b.HasKey("Id")
                        .HasName("pk_document");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_document_tenant_id");

                    b.ToTable("document", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CandidateEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_event_id");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end");

                    b.Property<Guid>("EventTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_type_id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_event");

                    b.HasIndex("CandidateEventId")
                        .HasDatabaseName("ix_event_candidate_event_id");

                    b.HasIndex("EventTypeId")
                        .HasDatabaseName("ix_event_event_type_id");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_event_location_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_event_tenant_id");

                    b.ToTable("event", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.EventGuestTenant", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("OwnerTenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_tenant_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("EventId", "TenantId")
                        .HasName("pk_event_guest_tenant");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_event_guest_tenant_tenant_id");

                    b.ToTable("event_guest_tenant", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.EventType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<int?>("DeployableAgeFrom")
                        .HasColumnType("integer")
                        .HasColumnName("deployable_age_from");

                    b.Property<int?>("DeployableAgeTo")
                        .HasColumnType("integer")
                        .HasColumnName("deployable_age_to");

                    b.Property<int?>("ExpectedVisitorCount")
                        .HasColumnType("integer")
                        .HasColumnName("expected_visitor_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("RequiredSkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("required_skill_id");

                    b.Property<int?>("TargetAgeFrom")
                        .HasColumnType("integer")
                        .HasColumnName("target_age_from");

                    b.Property<int?>("TargetAgeTo")
                        .HasColumnType("integer")
                        .HasColumnName("target_age_to");

                    b.Property<string>("TargetAudienceDescription")
                        .HasColumnType("text")
                        .HasColumnName("target_audience_description");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_event_type");

                    b.HasIndex("RequiredSkillId")
                        .HasDatabaseName("ix_event_type_required_skill_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_event_type_tenant_id");

                    b.ToTable("event_type", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Guideline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("SanitizedHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sanitized_html");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_guideline");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_guideline_tenant_id");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_guideline_updated_by");

                    b.ToTable("guideline", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("QrSlug")
                        .HasColumnType("text")
                        .HasColumnName("qr_slug");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_location");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_location_tenant_id");

                    b.ToTable("location", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<Guid>("ContextId")
                        .HasColumnType("uuid")
                        .HasColumnName("context_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_notification");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_idempotency_key");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_notification_person_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_notification_tenant_id");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ChatId")
                        .HasColumnType("text")
                        .HasColumnName("chat_id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("LastNamePrefix")
                        .HasColumnType("text")
                        .HasColumnName("last_name_prefix");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("PseudonymizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pseudonymized_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("StoppedOn")
                        .HasColumnType("date")
                        .HasColumnName("stopped_on");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_person");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_person_tenant_id");

                    b.ToTable("person", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.PersonAppRole", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("AppRole")
                        .HasColumnType("text")
                        .HasColumnName("app_role");

                    b.HasKey("PersonId", "AppRole")
                        .HasName("pk_person_app_role");

                    b.ToTable("person_app_role", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.PersonEventTypeException", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("EventTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_type_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RecordedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_person_id");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verdict");

                    b.HasKey("PersonId", "EventTypeId")
                        .HasName("pk_person_event_type_exception");

                    b.HasIndex("EventTypeId")
                        .HasDatabaseName("ix_person_event_type_exception_event_type_id");

                    b.HasIndex("RecordedByPersonId")
                        .HasDatabaseName("ix_person_event_type_exception_recorded_by_person_id");

                    b.ToTable("person_event_type_exception", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.PersonTeamRole", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("TeamRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_role_id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<bool>("SelfConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("self_confirmed");

                    b.HasKey("PersonId", "TeamRoleId")
                        .HasName("pk_person_team_role");

                    b.HasIndex("TeamRoleId")
                        .HasDatabaseName("ix_person_team_role_team_role_id");

                    b.ToTable("person_team_role", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Qualification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateOnly>("ObtainedOn")
                        .HasColumnType("date")
                        .HasColumnName("obtained_on");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("QualificationTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("qualification_type_id");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_qualification");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_qualification_person_id");

                    b.HasIndex("QualificationTypeId")
                        .HasDatabaseName("ix_qualification_qualification_type_id");

                    b.ToTable("qualification", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.QualificationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("DefaultValidityMonths")
                        .HasColumnType("integer")
                        .HasColumnName("default_validity_months");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("RequiredForTeamRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("required_for_team_role_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_qualification_type");

                    b.HasIndex("RequiredForTeamRoleId")
                        .HasDatabaseName("ix_qualification_type_required_for_team_role_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_qualification_type_tenant_id");

                    b.ToTable("qualification_type", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("RequiredCount")
                        .HasColumnType("integer")
                        .HasColumnName("required_count");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start");

                    b.Property<Guid>("TeamRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_role_id");

                    b.HasKey("Id")
                        .HasName("pk_shift");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_shift_event_id");

                    b.HasIndex("TeamRoleId")
                        .HasDatabaseName("ix_shift_team_role_id");

                    b.ToTable("shift", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.ShiftTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<int?>("DeployableAgeFrom")
                        .HasColumnType("integer")
                        .HasColumnName("deployable_age_from");

                    b.Property<int?>("DeployableAgeTo")
                        .HasColumnType("integer")
                        .HasColumnName("deployable_age_to");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<Guid>("EventTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_type_id");

                    b.Property<int>("StartOffsetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("start_offset_minutes");

                    b.Property<Guid>("TeamRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_role_id");

                    b.HasKey("Id")
                        .HasName("pk_shift_template");

                    b.HasIndex("EventTypeId")
                        .HasDatabaseName("ix_shift_template_event_type_id");

                    b.HasIndex("TeamRoleId")
                        .HasDatabaseName("ix_shift_template_team_role_id");

                    b.ToTable("shift_template", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.SwapRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid>("RequestedByPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_person_id");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("TargetPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_person_id");

                    b.HasKey("Id")
                        .HasName("pk_swap_request");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_swap_request_assignment_id");

                    b.HasIndex("RequestedByPersonId")
                        .HasDatabaseName("ix_swap_request_requested_by_person_id");

                    b.HasIndex("ShiftId")
                        .HasDatabaseName("ix_swap_request_shift_id");

                    b.HasIndex("TargetPersonId")
                        .HasDatabaseName("ix_swap_request_target_person_id");

                    b.ToTable("swap_request", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.TeamRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("VestColor")
                        .HasColumnType("text")
                        .HasColumnName("vest_color");

                    b.HasKey("Id")
                        .HasName("pk_team_role");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_team_role_tenant_id");

                    b.ToTable("team_role", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_slug");

                    b.ToTable("tenant", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.ActionToken", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_action_token_person_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Advisory", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.EventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_advisory_event_type_event_type_id");

                    b.HasOne("BccSafety.Infrastructure.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_advisory_tenant_tenant_id");

                    b.Navigation("EventType");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Assignment", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.Person", "AssignedByPerson")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_assignment_person_assigned_by");

                    b.HasOne("BccSafety.Infrastructure.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_person_person_id");

                    b.HasOne("BccSafety.Infrastructure.Entities.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_shift_shift_id");

                    b.Navigation("AssignedByPerson");

                    b.Navigation("Person");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.AuditLog", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.Person", "ActorPerson")
                        .WithMany()
                        .HasForeignKey("ActorPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_log_person_actor_person_id");

                    b.HasOne("BccSafety.Infrastructure.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audit_log_tenant_tenant_id");

                    b.Navigation("ActorPerson");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Availability", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_availability_person_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.CalendarMismatch", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_mismatch_event_event_id");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.CalendarSource", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_source_tenant_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.CandidateEvent", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.CalendarSource", "CalendarSource")
                        .WithMany()
                        .HasForeignKey("CalendarSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_candidate_event_calendar_source_calendar_source_id");

                    b.Navigation("CalendarSource");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.CheckIn", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_check_in_assignment_assignment_id");

                    b.HasOne("BccSafety.Infrastructure.Entities.Person", "ByPerson")
                        .WithMany()
                        .HasForeignKey("ByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_check_in_person_by_person_id");

                    b.Navigation("Assignment");

                    b.Navigation("ByPerson");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Contact", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contact_tenant_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Document", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_tenant_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Event", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.CandidateEvent", "CandidateEvent")
                        .WithMany()
                        .HasForeignKey("CandidateEventId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_event_candidate_event_candidate_event_id");

                    b.HasOne("BccSafety.Infrastructure.Entities.EventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_event_type_event_type_id");

                    b.HasOne("BccSafety.Infrastructure.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_location_location_id");

                    b.HasOne("BccSafety.Infrastructure.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_tenant_tenant_id");

                    b.Navigation("CandidateEvent");

                    b.Navigation("EventType");

                    b.Navigation("Location");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.EventGuestTenant", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_guest_tenant_event_event_id");

                    b.HasOne("BccSafety.Infrastructure.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_guest_tenant_tenant_tenant_id");

                    b.Navigation("Event");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.EventType", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.TeamRole", "RequiredSkill")
                        .WithMany()
                        .HasForeignKey("RequiredSkillId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_event_type_team_role_required_skill_id");

                    b.HasOne("BccSafety.Infrastructure.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_type_tenant_tenant_id");

                    b.Navigation("RequiredSkill");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Guideline", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guideline_tenant_tenant_id");

                    b.HasOne("BccSafety.Infrastructure.Entities.Person", "UpdatedByPerson")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_guideline_person_updated_by");

                    b.Navigation("Tenant");

                    b.Navigation("UpdatedByPerson");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Location", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_location_tenant_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Notification", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notification_person_person_id");

                    b.HasOne("BccSafety.Infrastructure.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_tenant_tenant_id");

                    b.Navigation("Person");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Person", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_tenant_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.PersonAppRole", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_app_role_person_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.PersonEventTypeException", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.EventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_event_type_exception_event_type_event_type_id");

                    b.HasOne("BccSafety.Infrastructure.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_event_type_exception_person_person_id");

                    b.HasOne("BccSafety.Infrastructure.Entities.Person", "RecordedByPerson")
                        .WithMany()
                        .HasForeignKey("RecordedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_person_event_type_exception_person_recorded_by_person_id");

                    b.Navigation("EventType");

                    b.Navigation("Person");

                    b.Navigation("RecordedByPerson");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.PersonTeamRole", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_team_role_person_person_id");

                    b.HasOne("BccSafety.Infrastructure.Entities.TeamRole", "TeamRole")
                        .WithMany()
                        .HasForeignKey("TeamRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_team_role_team_role_team_role_id");

                    b.Navigation("Person");

                    b.Navigation("TeamRole");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Qualification", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_qualification_person_person_id");

                    b.HasOne("BccSafety.Infrastructure.Entities.QualificationType", "QualificationType")
                        .WithMany()
                        .HasForeignKey("QualificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_qualification_qualification_type_qualification_type_id");

                    b.Navigation("Person");

                    b.Navigation("QualificationType");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.QualificationType", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.TeamRole", "RequiredForTeamRole")
                        .WithMany()
                        .HasForeignKey("RequiredForTeamRoleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_qualification_type_team_role_required_for_team_role_id");

                    b.HasOne("BccSafety.Infrastructure.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_qualification_type_tenant_tenant_id");

                    b.Navigation("RequiredForTeamRole");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.Shift", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shift_event_event_id");

                    b.HasOne("BccSafety.Infrastructure.Entities.TeamRole", "TeamRole")
                        .WithMany()
                        .HasForeignKey("TeamRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shift_team_role_team_role_id");

                    b.Navigation("Event");

                    b.Navigation("TeamRole");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.ShiftTemplate", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.EventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shift_template_event_type_event_type_id");

                    b.HasOne("BccSafety.Infrastructure.Entities.TeamRole", "TeamRole")
                        .WithMany()
                        .HasForeignKey("TeamRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shift_template_team_role_team_role_id");

                    b.Navigation("EventType");

                    b.Navigation("TeamRole");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.SwapRequest", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_swap_request_assignment_assignment_id");

                    b.HasOne("BccSafety.Infrastructure.Entities.Person", "RequestedByPerson")
                        .WithMany()
                        .HasForeignKey("RequestedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_swap_request_person_requested_by_person_id");

                    b.HasOne("BccSafety.Infrastructure.Entities.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_swap_request_shift_shift_id");

                    b.HasOne("BccSafety.Infrastructure.Entities.Person", "TargetPerson")
                        .WithMany()
                        .HasForeignKey("TargetPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_swap_request_person_target_person_id");

                    b.Navigation("Assignment");

                    b.Navigation("RequestedByPerson");

                    b.Navigation("Shift");

                    b.Navigation("TargetPerson");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entities.TeamRole", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_role_tenant_tenant_id");

                    b.Navigation("Tenant");
                });
#pragma warning restore 612, 618
        }
    }
}
