// <auto-generated />
using System;
using BccSafety.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BccSafety.Infrastructure.Migrations
{
    [DbContext(typeof(BccSafetyDbContext))]
    [Migration("20260828124649_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Aandachtspunt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("EvenementtypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("evenementtype_id");

                    b.Property<DateOnly>("GeldigTot")
                        .HasColumnType("date")
                        .HasColumnName("geldig_tot");

                    b.Property<DateOnly>("GeldigVan")
                        .HasColumnType("date")
                        .HasColumnName("geldig_van");

                    b.Property<int>("Prioriteit")
                        .HasColumnType("integer")
                        .HasColumnName("prioriteit");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tekst");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titel");

                    b.HasKey("Id")
                        .HasName("pk_aandachtspunt");

                    b.HasIndex("EvenementtypeId")
                        .HasDatabaseName("ix_aandachtspunt_evenementtype_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_aandachtspunt_tenant_id");

                    b.ToTable("aandachtspunt", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.AgendaAfwijking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("AfgehandeldOp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("afgehandeld_op");

                    b.Property<Guid>("EvenementId")
                        .HasColumnType("uuid")
                        .HasColumnName("evenement_id");

                    b.Property<DateTimeOffset>("GedetecteerdOp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gedetecteerd_op");

                    b.Property<string>("Soort")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("soort");

                    b.HasKey("Id")
                        .HasName("pk_agenda_afwijking");

                    b.HasIndex("EvenementId")
                        .HasDatabaseName("ix_agenda_afwijking_evenement_id");

                    b.ToTable("agenda_afwijking", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.AgendaBron", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Actief")
                        .HasColumnType("boolean")
                        .HasColumnName("actief");

                    b.Property<string>("IcsUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ics_url");

                    b.Property<DateTimeOffset?>("LaatsteSyncOp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("laatste_sync_op");

                    b.Property<string>("LaatsteSyncStatus")
                        .HasColumnType("text")
                        .HasColumnName("laatste_sync_status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_agenda_bron");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_agenda_bron_tenant_id");

                    b.ToTable("agenda_bron", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Auditlog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Actie")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actie");

                    b.Property<Guid?>("ActorPersoonId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_persoon_id");

                    b.Property<string>("Entiteit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entiteit");

                    b.Property<Guid>("EntiteitId")
                        .HasColumnType("uuid")
                        .HasColumnName("entiteit_id");

                    b.Property<string>("NieuweWaarde")
                        .HasColumnType("jsonb")
                        .HasColumnName("nieuwe_waarde");

                    b.Property<string>("OudeWaarde")
                        .HasColumnType("jsonb")
                        .HasColumnName("oude_waarde");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("Tijdstip")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tijdstip");

                    b.HasKey("Id")
                        .HasName("pk_auditlog");

                    b.HasIndex("ActorPersoonId")
                        .HasDatabaseName("ix_auditlog_actor_persoon_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_auditlog_tenant_id");

                    b.ToTable("auditlog", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Beschikbaarheid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Notitie")
                        .HasColumnType("text")
                        .HasColumnName("notitie");

                    b.Property<Guid>("PersoonId")
                        .HasColumnType("uuid")
                        .HasColumnName("persoon_id");

                    b.Property<string>("Soort")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("soort");

                    b.Property<DateTimeOffset>("Tot")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tot");

                    b.Property<DateTimeOffset>("Van")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("van");

                    b.HasKey("Id")
                        .HasName("pk_beschikbaarheid");

                    b.HasIndex("PersoonId")
                        .HasDatabaseName("ix_beschikbaarheid_persoon_id");

                    b.ToTable("beschikbaarheid", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Checkin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("DoorPersoonId")
                        .HasColumnType("uuid")
                        .HasColumnName("door_persoon_id");

                    b.Property<string>("Methode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("methode");

                    b.Property<DateTimeOffset>("Tijdstip")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tijdstip");

                    b.Property<Guid>("ToewijzingId")
                        .HasColumnType("uuid")
                        .HasColumnName("toewijzing_id");

                    b.HasKey("Id")
                        .HasName("pk_checkin");

                    b.HasIndex("DoorPersoonId")
                        .HasDatabaseName("ix_checkin_door_persoon_id");

                    b.HasIndex("ToewijzingId")
                        .HasDatabaseName("ix_checkin_toewijzing_id");

                    b.ToTable("checkin", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Functie")
                        .HasColumnType("text")
                        .HasColumnName("functie");

                    b.Property<bool>("IsNoodnummer")
                        .HasColumnType("boolean")
                        .HasColumnName("is_noodnummer");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("naam");

                    b.Property<string>("Telefoon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefoon");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Volgorde")
                        .HasColumnType("integer")
                        .HasColumnName("volgorde");

                    b.HasKey("Id")
                        .HasName("pk_contact");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_contact_tenant_id");

                    b.ToTable("contact", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Dienst", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("BenodigdAantal")
                        .HasColumnType("integer")
                        .HasColumnName("benodigd_aantal");

                    b.Property<DateTimeOffset>("Eind")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eind");

                    b.Property<Guid>("EvenementId")
                        .HasColumnType("uuid")
                        .HasColumnName("evenement_id");

                    b.Property<string>("Notitie")
                        .HasColumnType("text")
                        .HasColumnName("notitie");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start");

                    b.Property<Guid>("TeamrolId")
                        .HasColumnType("uuid")
                        .HasColumnName("teamrol_id");

                    b.HasKey("Id")
                        .HasName("pk_dienst");

                    b.HasIndex("EvenementId")
                        .HasDatabaseName("ix_dienst_evenement_id");

                    b.HasIndex("TeamrolId")
                        .HasDatabaseName("ix_dienst_teamrol_id");

                    b.ToTable("dienst", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Dienstsjabloon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Aantal")
                        .HasColumnType("integer")
                        .HasColumnName("aantal");

                    b.Property<int>("DuurMinuten")
                        .HasColumnType("integer")
                        .HasColumnName("duur_minuten");

                    b.Property<Guid>("EvenementtypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("evenementtype_id");

                    b.Property<int?>("InzetbaarLeeftijdTot")
                        .HasColumnType("integer")
                        .HasColumnName("inzetbaar_leeftijd_tot");

                    b.Property<int?>("InzetbaarLeeftijdVan")
                        .HasColumnType("integer")
                        .HasColumnName("inzetbaar_leeftijd_van");

                    b.Property<int>("StartOffsetMinuten")
                        .HasColumnType("integer")
                        .HasColumnName("start_offset_minuten");

                    b.Property<Guid>("TeamrolId")
                        .HasColumnType("uuid")
                        .HasColumnName("teamrol_id");

                    b.HasKey("Id")
                        .HasName("pk_dienstsjabloon");

                    b.HasIndex("EvenementtypeId")
                        .HasDatabaseName("ix_dienstsjabloon_evenementtype_id");

                    b.HasIndex("TeamrolId")
                        .HasDatabaseName("ix_dienstsjabloon_teamrol_id");

                    b.ToTable("dienstsjabloon", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BestandRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bestand_ref");

                    b.Property<DateTimeOffset>("GepubliceerdOp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gepubliceerd_op");

                    b.Property<bool>("IsActueel")
                        .HasColumnType("boolean")
                        .HasColumnName("is_actueel");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titel");

                    b.Property<string>("VersieLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("versie_label");

                    b.HasKey("Id")
                        .HasName("pk_document");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_document_tenant_id");

                    b.ToTable("document", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Evenement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Bron")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bron");

                    b.Property<DateTimeOffset>("Eind")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eind");

                    b.Property<Guid>("EvenementtypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("evenementtype_id");

                    b.Property<Guid?>("KandidaatEvenementId")
                        .HasColumnType("uuid")
                        .HasColumnName("kandidaat_evenement_id");

                    b.Property<Guid>("LocatieId")
                        .HasColumnType("uuid")
                        .HasColumnName("locatie_id");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titel");

                    b.HasKey("Id")
                        .HasName("pk_evenement");

                    b.HasIndex("EvenementtypeId")
                        .HasDatabaseName("ix_evenement_evenementtype_id");

                    b.HasIndex("KandidaatEvenementId")
                        .HasDatabaseName("ix_evenement_kandidaat_evenement_id");

                    b.HasIndex("LocatieId")
                        .HasDatabaseName("ix_evenement_locatie_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_evenement_tenant_id");

                    b.ToTable("evenement", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.EvenementGasttenant", b =>
                {
                    b.Property<Guid>("EvenementId")
                        .HasColumnType("uuid")
                        .HasColumnName("evenement_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("EigenaarTenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("eigenaar_tenant_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("EvenementId", "TenantId")
                        .HasName("pk_evenement_gasttenant");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_evenement_gasttenant_tenant_id");

                    b.ToTable("evenement_gasttenant", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Evenementtype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Actief")
                        .HasColumnType("boolean")
                        .HasColumnName("actief");

                    b.Property<int?>("DoelgroepLeeftijdTot")
                        .HasColumnType("integer")
                        .HasColumnName("doelgroep_leeftijd_tot");

                    b.Property<int?>("DoelgroepLeeftijdVan")
                        .HasColumnType("integer")
                        .HasColumnName("doelgroep_leeftijd_van");

                    b.Property<string>("DoelgroepOmschrijving")
                        .HasColumnType("text")
                        .HasColumnName("doelgroep_omschrijving");

                    b.Property<int?>("InzetbaarLeeftijdTot")
                        .HasColumnType("integer")
                        .HasColumnName("inzetbaar_leeftijd_tot");

                    b.Property<int?>("InzetbaarLeeftijdVan")
                        .HasColumnType("integer")
                        .HasColumnName("inzetbaar_leeftijd_van");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("naam");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("VereisteBekwaamheidId")
                        .HasColumnType("uuid")
                        .HasColumnName("vereiste_bekwaamheid_id");

                    b.Property<int?>("VerwachtAantalBezoekers")
                        .HasColumnType("integer")
                        .HasColumnName("verwacht_aantal_bezoekers");

                    b.HasKey("Id")
                        .HasName("pk_evenementtype");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_evenementtype_tenant_id");

                    b.HasIndex("VereisteBekwaamheidId")
                        .HasDatabaseName("ix_evenementtype_vereiste_bekwaamheid_id");

                    b.ToTable("evenementtype", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.KandidaatEvenement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AgendaBronId")
                        .HasColumnType("uuid")
                        .HasColumnName("agenda_bron_id");

                    b.Property<DateTimeOffset>("Eind")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eind");

                    b.Property<string>("IcsUid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ics_uid");

                    b.Property<string>("InhoudHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("inhoud_hash");

                    b.Property<string>("LocatieTekst")
                        .HasColumnType("text")
                        .HasColumnName("locatie_tekst");

                    b.Property<string>("RecurrenceId")
                        .HasColumnType("text")
                        .HasColumnName("recurrence_id");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titel");

                    b.HasKey("Id")
                        .HasName("pk_kandidaat_evenement");

                    b.HasIndex("AgendaBronId", "IcsUid", "RecurrenceId")
                        .IsUnique()
                        .HasDatabaseName("ix_kandidaat_evenement_agenda_bron_id_ics_uid_recurrence_id");

                    b.ToTable("kandidaat_evenement", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Kwalificatie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly>("BehaaldOp")
                        .HasColumnType("date")
                        .HasColumnName("behaald_op");

                    b.Property<DateOnly?>("GeldigTot")
                        .HasColumnType("date")
                        .HasColumnName("geldig_tot");

                    b.Property<Guid>("KwalificatieTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("kwalificatie_type_id");

                    b.Property<string>("Notitie")
                        .HasColumnType("text")
                        .HasColumnName("notitie");

                    b.Property<Guid>("PersoonId")
                        .HasColumnType("uuid")
                        .HasColumnName("persoon_id");

                    b.HasKey("Id")
                        .HasName("pk_kwalificatie");

                    b.HasIndex("KwalificatieTypeId")
                        .HasDatabaseName("ix_kwalificatie_kwalificatie_type_id");

                    b.HasIndex("PersoonId")
                        .HasDatabaseName("ix_kwalificatie_persoon_id");

                    b.ToTable("kwalificatie", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.KwalificatieType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("naam");

                    b.Property<int?>("StandaardGeldigheidMaanden")
                        .HasColumnType("integer")
                        .HasColumnName("standaard_geldigheid_maanden");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("VereistVoorTeamrolId")
                        .HasColumnType("uuid")
                        .HasColumnName("vereist_voor_teamrol_id");

                    b.HasKey("Id")
                        .HasName("pk_kwalificatie_type");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_kwalificatie_type_tenant_id");

                    b.HasIndex("VereistVoorTeamrolId")
                        .HasDatabaseName("ix_kwalificatie_type_vereist_voor_teamrol_id");

                    b.ToTable("kwalificatie_type", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Locatie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Adres")
                        .HasColumnType("text")
                        .HasColumnName("adres");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("naam");

                    b.Property<string>("QrSlug")
                        .HasColumnType("text")
                        .HasColumnName("qr_slug");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_locatie");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_locatie_tenant_id");

                    b.ToTable("locatie", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Notificatie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ContextId")
                        .HasColumnType("uuid")
                        .HasColumnName("context_id");

                    b.Property<DateTimeOffset>("GeplandOp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gepland_op");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Kanaal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kanaal");

                    b.Property<Guid>("PersoonId")
                        .HasColumnType("uuid")
                        .HasColumnName("persoon_id");

                    b.Property<string>("Sjabloon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sjabloon");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("VerzondenOp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verzonden_op");

                    b.HasKey("Id")
                        .HasName("pk_notificatie");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_notificatie_idempotency_key");

                    b.HasIndex("PersoonId")
                        .HasDatabaseName("ix_notificatie_persoon_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_notificatie_tenant_id");

                    b.ToTable("notificatie", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Persoon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("achternaam");

                    b.Property<string>("ChatId")
                        .HasColumnType("text")
                        .HasColumnName("chat_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateOnly>("Geboortedatum")
                        .HasColumnType("date")
                        .HasColumnName("geboortedatum");

                    b.Property<DateTimeOffset?>("GepseudonimiseerdOp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gepseudonimiseerd_op");

                    b.Property<DateOnly?>("GestoptOp")
                        .HasColumnType("date")
                        .HasColumnName("gestopt_op");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Telefoon")
                        .HasColumnType("text")
                        .HasColumnName("telefoon");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tussenvoegsel")
                        .HasColumnType("text")
                        .HasColumnName("tussenvoegsel");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("voornaam");

                    b.HasKey("Id")
                        .HasName("pk_persoon");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_persoon_tenant_id");

                    b.ToTable("persoon", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.PersoonApprol", b =>
                {
                    b.Property<Guid>("PersoonId")
                        .HasColumnType("uuid")
                        .HasColumnName("persoon_id");

                    b.Property<string>("Approl")
                        .HasColumnType("text")
                        .HasColumnName("approl");

                    b.HasKey("PersoonId", "Approl")
                        .HasName("pk_persoon_approl");

                    b.ToTable("persoon_approl", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.PersoonEvenementtypeUitzondering", b =>
                {
                    b.Property<Guid>("PersoonId")
                        .HasColumnType("uuid")
                        .HasColumnName("persoon_id");

                    b.Property<Guid>("EvenementtypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("evenementtype_id");

                    b.Property<string>("Oordeel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("oordeel");

                    b.Property<string>("Reden")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reden");

                    b.Property<Guid>("VastgelegdDoorPersoonId")
                        .HasColumnType("uuid")
                        .HasColumnName("vastgelegd_door_persoon_id");

                    b.Property<DateTimeOffset>("VastgelegdOp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vastgelegd_op");

                    b.HasKey("PersoonId", "EvenementtypeId")
                        .HasName("pk_persoon_evenementtype_uitzondering");

                    b.HasIndex("EvenementtypeId")
                        .HasDatabaseName("ix_persoon_evenementtype_uitzondering_evenementtype_id");

                    b.HasIndex("VastgelegdDoorPersoonId")
                        .HasDatabaseName("ix_persoon_evenementtype_uitzondering_vastgelegd_door_persoon_");

                    b.ToTable("persoon_evenementtype_uitzondering", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.PersoonTeamrol", b =>
                {
                    b.Property<Guid>("PersoonId")
                        .HasColumnType("uuid")
                        .HasColumnName("persoon_id");

                    b.Property<Guid>("TeamrolId")
                        .HasColumnType("uuid")
                        .HasColumnName("teamrol_id");

                    b.Property<bool>("BevestigdDoorPersoonZelf")
                        .HasColumnType("boolean")
                        .HasColumnName("bevestigd_door_persoon_zelf");

                    b.Property<DateTimeOffset?>("BevestigdOp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bevestigd_op");

                    b.HasKey("PersoonId", "TeamrolId")
                        .HasName("pk_persoon_teamrol");

                    b.HasIndex("TeamrolId")
                        .HasDatabaseName("ix_persoon_teamrol_teamrol_id");

                    b.ToTable("persoon_teamrol", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Richtlijn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BijgewerktDoor")
                        .HasColumnType("uuid")
                        .HasColumnName("bijgewerkt_door");

                    b.Property<DateTimeOffset?>("GepubliceerdOp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gepubliceerd_op");

                    b.Property<string>("HtmlGesaniteerd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html_gesaniteerd");

                    b.Property<string>("Soort")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("soort");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titel");

                    b.Property<int>("Versie")
                        .HasColumnType("integer")
                        .HasColumnName("versie");

                    b.Property<int>("Volgorde")
                        .HasColumnType("integer")
                        .HasColumnName("volgorde");

                    b.Property<string>("Zichtbaarheid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zichtbaarheid");

                    b.HasKey("Id")
                        .HasName("pk_richtlijn");

                    b.HasIndex("BijgewerktDoor")
                        .HasDatabaseName("ix_richtlijn_bijgewerkt_door");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_richtlijn_tenant_id");

                    b.ToTable("richtlijn", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Ruilverzoek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AangevraagdDoorPersoonId")
                        .HasColumnType("uuid")
                        .HasColumnName("aangevraagd_door_persoon_id");

                    b.Property<Guid>("DienstId")
                        .HasColumnType("uuid")
                        .HasColumnName("dienst_id");

                    b.Property<Guid?>("DoelPersoonId")
                        .HasColumnType("uuid")
                        .HasColumnName("doel_persoon_id");

                    b.Property<string>("Soort")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("soort");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("ToewijzingId")
                        .HasColumnType("uuid")
                        .HasColumnName("toewijzing_id");

                    b.Property<DateTimeOffset>("VerlooptOp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verloopt_op");

                    b.HasKey("Id")
                        .HasName("pk_ruilverzoek");

                    b.HasIndex("AangevraagdDoorPersoonId")
                        .HasDatabaseName("ix_ruilverzoek_aangevraagd_door_persoon_id");

                    b.HasIndex("DienstId")
                        .HasDatabaseName("ix_ruilverzoek_dienst_id");

                    b.HasIndex("DoelPersoonId")
                        .HasDatabaseName("ix_ruilverzoek_doel_persoon_id");

                    b.HasIndex("ToewijzingId")
                        .HasDatabaseName("ix_ruilverzoek_toewijzing_id");

                    b.ToTable("ruilverzoek", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Teamrol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Actief")
                        .HasColumnType("boolean")
                        .HasColumnName("actief");

                    b.Property<string>("HesjeKleur")
                        .HasColumnType("text")
                        .HasColumnName("hesje_kleur");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("naam");

                    b.Property<string>("Soort")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("soort");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_teamrol");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_teamrol_tenant_id");

                    b.ToTable("teamrol", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("AangemaaktOp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aangemaakt_op");

                    b.Property<bool>("Actief")
                        .HasColumnType("boolean")
                        .HasColumnName("actief");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("naam");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_slug");

                    b.ToTable("tenant", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Toewijzing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("AfgemeldOp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("afgemeld_op");

                    b.Property<string>("AfmeldReden")
                        .HasColumnType("text")
                        .HasColumnName("afmeld_reden");

                    b.Property<Guid>("DienstId")
                        .HasColumnType("uuid")
                        .HasColumnName("dienst_id");

                    b.Property<Guid>("PersoonId")
                        .HasColumnType("uuid")
                        .HasColumnName("persoon_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("ToegewezenDoor")
                        .HasColumnType("uuid")
                        .HasColumnName("toegewezen_door");

                    b.Property<DateTimeOffset>("ToegewezenOp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("toegewezen_op");

                    b.Property<string>("WaarschuwingenBijToewijzing")
                        .HasColumnType("jsonb")
                        .HasColumnName("waarschuwingen_bij_toewijzing");

                    b.HasKey("Id")
                        .HasName("pk_toewijzing");

                    b.HasIndex("DienstId")
                        .HasDatabaseName("ix_toewijzing_dienst_id");

                    b.HasIndex("PersoonId")
                        .HasDatabaseName("ix_toewijzing_persoon_id");

                    b.HasIndex("ToegewezenDoor")
                        .HasDatabaseName("ix_toewijzing_toegewezen_door");

                    b.ToTable("toewijzing", (string)null);
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Aandachtspunt", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Evenementtype", "Evenementtype")
                        .WithMany()
                        .HasForeignKey("EvenementtypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_aandachtspunt_evenementtype_evenementtype_id");

                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aandachtspunt_tenant_tenant_id");

                    b.Navigation("Evenementtype");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.AgendaAfwijking", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Evenement", "Evenement")
                        .WithMany()
                        .HasForeignKey("EvenementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agenda_afwijking_evenement_evenement_id");

                    b.Navigation("Evenement");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.AgendaBron", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agenda_bron_tenant_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Auditlog", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Persoon", "ActorPersoon")
                        .WithMany()
                        .HasForeignKey("ActorPersoonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_auditlog_persoon_actor_persoon_id");

                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auditlog_tenant_tenant_id");

                    b.Navigation("ActorPersoon");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Beschikbaarheid", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Persoon", "Persoon")
                        .WithMany()
                        .HasForeignKey("PersoonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_beschikbaarheid_persoon_persoon_id");

                    b.Navigation("Persoon");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Checkin", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Persoon", "DoorPersoon")
                        .WithMany()
                        .HasForeignKey("DoorPersoonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_checkin_persoon_door_persoon_id");

                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Toewijzing", "Toewijzing")
                        .WithMany()
                        .HasForeignKey("ToewijzingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_checkin_toewijzing_toewijzing_id");

                    b.Navigation("DoorPersoon");

                    b.Navigation("Toewijzing");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Contact", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contact_tenant_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Dienst", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Evenement", "Evenement")
                        .WithMany()
                        .HasForeignKey("EvenementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dienst_evenement_evenement_id");

                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Teamrol", "Teamrol")
                        .WithMany()
                        .HasForeignKey("TeamrolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dienst_teamrol_teamrol_id");

                    b.Navigation("Evenement");

                    b.Navigation("Teamrol");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Dienstsjabloon", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Evenementtype", "Evenementtype")
                        .WithMany()
                        .HasForeignKey("EvenementtypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dienstsjabloon_evenementtype_evenementtype_id");

                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Teamrol", "Teamrol")
                        .WithMany()
                        .HasForeignKey("TeamrolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dienstsjabloon_teamrol_teamrol_id");

                    b.Navigation("Evenementtype");

                    b.Navigation("Teamrol");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Document", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_tenant_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Evenement", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Evenementtype", "Evenementtype")
                        .WithMany()
                        .HasForeignKey("EvenementtypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_evenement_evenementtype_evenementtype_id");

                    b.HasOne("BccSafety.Infrastructure.Entiteiten.KandidaatEvenement", "KandidaatEvenement")
                        .WithMany()
                        .HasForeignKey("KandidaatEvenementId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_evenement_kandidaat_evenement_kandidaat_evenement_id");

                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Locatie", "Locatie")
                        .WithMany()
                        .HasForeignKey("LocatieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_evenement_locatie_locatie_id");

                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_evenement_tenant_tenant_id");

                    b.Navigation("Evenementtype");

                    b.Navigation("KandidaatEvenement");

                    b.Navigation("Locatie");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.EvenementGasttenant", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Evenement", "Evenement")
                        .WithMany()
                        .HasForeignKey("EvenementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_evenement_gasttenant_evenement_evenement_id");

                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_evenement_gasttenant_tenant_tenant_id");

                    b.Navigation("Evenement");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Evenementtype", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_evenementtype_tenant_tenant_id");

                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Teamrol", "VereisteBekwaamheid")
                        .WithMany()
                        .HasForeignKey("VereisteBekwaamheidId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_evenementtype_teamrol_vereiste_bekwaamheid_id");

                    b.Navigation("Tenant");

                    b.Navigation("VereisteBekwaamheid");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.KandidaatEvenement", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.AgendaBron", "AgendaBron")
                        .WithMany()
                        .HasForeignKey("AgendaBronId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kandidaat_evenement_agenda_bron_agenda_bron_id");

                    b.Navigation("AgendaBron");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Kwalificatie", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.KwalificatieType", "KwalificatieType")
                        .WithMany()
                        .HasForeignKey("KwalificatieTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kwalificatie_kwalificatie_type_kwalificatie_type_id");

                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Persoon", "Persoon")
                        .WithMany()
                        .HasForeignKey("PersoonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kwalificatie_persoon_persoon_id");

                    b.Navigation("KwalificatieType");

                    b.Navigation("Persoon");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.KwalificatieType", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kwalificatie_type_tenant_tenant_id");

                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Teamrol", "VereistVoorTeamrol")
                        .WithMany()
                        .HasForeignKey("VereistVoorTeamrolId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_kwalificatie_type_teamrol_vereist_voor_teamrol_id");

                    b.Navigation("Tenant");

                    b.Navigation("VereistVoorTeamrol");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Locatie", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_locatie_tenant_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Notificatie", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Persoon", "Persoon")
                        .WithMany()
                        .HasForeignKey("PersoonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notificatie_persoon_persoon_id");

                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notificatie_tenant_tenant_id");

                    b.Navigation("Persoon");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Persoon", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_persoon_tenant_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.PersoonApprol", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Persoon", "Persoon")
                        .WithMany()
                        .HasForeignKey("PersoonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_persoon_approl_persoon_persoon_id");

                    b.Navigation("Persoon");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.PersoonEvenementtypeUitzondering", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Evenementtype", "Evenementtype")
                        .WithMany()
                        .HasForeignKey("EvenementtypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_persoon_evenementtype_uitzondering_evenementtype_evenementt");

                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Persoon", "Persoon")
                        .WithMany()
                        .HasForeignKey("PersoonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_persoon_evenementtype_uitzondering_persoon_persoon_id");

                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Persoon", "VastgelegdDoorPersoon")
                        .WithMany()
                        .HasForeignKey("VastgelegdDoorPersoonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_persoon_evenementtype_uitzondering_persoon_vastgelegd_door_");

                    b.Navigation("Evenementtype");

                    b.Navigation("Persoon");

                    b.Navigation("VastgelegdDoorPersoon");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.PersoonTeamrol", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Persoon", "Persoon")
                        .WithMany()
                        .HasForeignKey("PersoonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_persoon_teamrol_persoon_persoon_id");

                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Teamrol", "Teamrol")
                        .WithMany()
                        .HasForeignKey("TeamrolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_persoon_teamrol_teamrol_teamrol_id");

                    b.Navigation("Persoon");

                    b.Navigation("Teamrol");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Richtlijn", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Persoon", "BijgewerktDoorPersoon")
                        .WithMany()
                        .HasForeignKey("BijgewerktDoor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_richtlijn_persoon_bijgewerkt_door");

                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_richtlijn_tenant_tenant_id");

                    b.Navigation("BijgewerktDoorPersoon");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Ruilverzoek", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Persoon", "AangevraagdDoorPersoon")
                        .WithMany()
                        .HasForeignKey("AangevraagdDoorPersoonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ruilverzoek_persoon_aangevraagd_door_persoon_id");

                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Dienst", "Dienst")
                        .WithMany()
                        .HasForeignKey("DienstId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ruilverzoek_dienst_dienst_id");

                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Persoon", "DoelPersoon")
                        .WithMany()
                        .HasForeignKey("DoelPersoonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ruilverzoek_persoon_doel_persoon_id");

                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Toewijzing", "Toewijzing")
                        .WithMany()
                        .HasForeignKey("ToewijzingId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ruilverzoek_toewijzing_toewijzing_id");

                    b.Navigation("AangevraagdDoorPersoon");

                    b.Navigation("Dienst");

                    b.Navigation("DoelPersoon");

                    b.Navigation("Toewijzing");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Teamrol", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teamrol_tenant_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BccSafety.Infrastructure.Entiteiten.Toewijzing", b =>
                {
                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Dienst", "Dienst")
                        .WithMany()
                        .HasForeignKey("DienstId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_toewijzing_dienst_dienst_id");

                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Persoon", "Persoon")
                        .WithMany()
                        .HasForeignKey("PersoonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_toewijzing_persoon_persoon_id");

                    b.HasOne("BccSafety.Infrastructure.Entiteiten.Persoon", "ToegewezenDoorPersoon")
                        .WithMany()
                        .HasForeignKey("ToegewezenDoor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_toewijzing_persoon_toegewezen_door");

                    b.Navigation("Dienst");

                    b.Navigation("Persoon");

                    b.Navigation("ToegewezenDoorPersoon");
                });
#pragma warning restore 612, 618
        }
    }
}
